#!/usr/bin/env python3
"""
Generate install.yaml: everything needed to run AgentBox, in one file.

    kubectl apply -f https://github.com/never2average/agentbox/releases/latest/download/install.yaml

Concatenates crds/ and deploy/ and pins the controller image to a version, so an
adopter never has to clone the repository.

Usage:
    python tools/generate_install.py [--version v0.1.0] [--check]
"""
import argparse
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
CRD_DIR = ROOT / "crds"
DEPLOY_DIR = ROOT / "deploy"
TARGET = ROOT / "install.yaml"

IMAGE_REPO = "ghcr.io/never2average/agentbox-controller"
DEFAULT_VERSION = "latest"


def documents(directory: Path):
    """Every YAML document in a directory, skipping kustomization files."""
    for path in sorted(directory.glob("*.yaml")):
        if path.name == "kustomization.yaml":
            continue
        for doc in yaml.safe_load_all(path.read_text()):
            if doc:
                yield path.name, doc


def pin_image(doc, version):
    """Point the controller Deployment at a specific image tag."""
    if doc.get("kind") != "Deployment":
        return doc
    for container in doc["spec"]["template"]["spec"]["containers"]:
        if container["name"] == "controller":
            container["image"] = f"{IMAGE_REPO}:{version}"
    return doc


def build(version):
    """Render the combined install manifest."""
    header = (
        "# AgentBox install manifest\n"
        f"# Version: {version}\n"
        "#\n"
        "# Generated by tools/generate_install.py from crds/ and deploy/.\n"
        "# Do not edit by hand.\n"
        "#\n"
        "#   kubectl apply -f install.yaml\n"
        "#\n"
        "# This installs the 16 CRDs, the agentbox-system namespace, RBAC for the\n"
        "# controller, and the controller itself.\n"
    )

    chunks = [header]
    for source, doc in list(documents(CRD_DIR)) + list(documents(DEPLOY_DIR)):
        doc = pin_image(doc, version)
        chunks.append(f"---\n# from {source}\n" +
                      yaml.dump(doc, default_flow_style=False, sort_keys=False, width=100))
    return "\n".join(chunks)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--version", default=DEFAULT_VERSION,
                        help="image tag to pin, e.g. v0.1.0")
    parser.add_argument("--check", action="store_true",
                        help="fail if install.yaml is out of date instead of writing")
    args = parser.parse_args()

    content = build(args.version)

    if args.check:
        if not TARGET.exists() or TARGET.read_text() != content:
            print("install.yaml is out of date")
            return 1
        print("install.yaml is up to date")
        return 0

    TARGET.write_text(content)
    count = content.count("\n---\n") + 1
    print(f"wrote install.yaml ({count} objects, image {IMAGE_REPO}:{args.version})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
